DROP TABLE checkin_intaketime IF EXISTS;
DROP TABLE check_in_symptom_times IF EXISTS;
/* delete patient before check-in */
DROP TABLE patient_doctor IF EXISTS;
DROP TABLE patient_medications IF EXISTS;
DROP TABLE patient IF EXISTS;
DROP TABLE check_in IF EXISTS;
DROP TABLE doctor IF EXISTS;

DROP TABLE medication_intake_times IF EXISTS;
DROP TABLE intake_time IF EXISTS;

/* delete medication before medicament */
DROP TABLE medication IF EXISTS;
DROP TABLE medicament IF EXISTS;
DROP TABLE role IF EXISTS;
DROP TABLE symptom IF EXISTS;
DROP TABLE symptom_time IF EXISTS;
DROP TABLE video IF EXISTS;

CREATE TABLE check_in (
    id bigint generated BY DEFAULT AS IDENTITY (start WITH 1),
    PRIMARY KEY (id)
);
CREATE TABLE check_in_symptom_times (
    checkin_id bigint NOT NULL,
    symptom_times_id bigint NOT NULL
);
CREATE TABLE checkin_intaketime (
    checkin_id bigint NOT NULL,
    intaketime_id bigint NOT NULL
);
CREATE TABLE checkin_symptom (
    checkin_id bigint NOT NULL,
    symptom_id bigint NOT NULL
);
CREATE TABLE doctor (
    id bigint generated BY DEFAULT AS IDENTITY (start WITH 1),
    date_of_birth timestamp,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    username VARCHAR(255),
    password VARCHAR(255),
    PRIMARY KEY (id));
CREATE TABLE doctor_roles (
    doctor_id bigint NOT NULL,
    roles_id bigint NOT NULL
);
CREATE TABLE intake_time (
    id bigint generated BY DEFAULT AS IDENTITY (start WITH 1),
    timestamp timestamp,
    medication_id bigint NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE medicament (
    id bigint generated BY DEFAULT AS IDENTITY (start WITH 1),
    name VARCHAR(255),
    PRIMARY KEY (id)
);
CREATE TABLE medication (
    id bigint generated BY DEFAULT AS IDENTITY (start WITH 1),
    medicament_id bigint,
    PRIMARY KEY (id)
);
CREATE TABLE medication_intake_times (
    medication_id bigint NOT NULL,
    intake_times_id bigint NOT NULL
);
CREATE TABLE patient (
    id bigint generated BY DEFAULT AS IDENTITY (start WITH 1),
    date_of_birth timestamp,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    username VARCHAR(255),
    password VARCHAR(255),
    medical_record_number VARCHAR(255),
    check_in_id bigint,
    PRIMARY KEY (id)
);
CREATE TABLE patient_doctor (
    patient_id bigint NOT NULL,
    doctor_id bigint NOT NULL
);
CREATE TABLE patient_medications (
    patient_id bigint NOT NULL,
    medications_id bigint NOT NULL
);
CREATE TABLE patient_roles (
    patient_id bigint NOT NULL,
    roles_id bigint NOT NULL);

CREATE TABLE role (
    id bigint generated BY DEFAULT AS IDENTITY (start WITH 1),
    name VARCHAR(255),
    PRIMARY KEY (id)
);
CREATE TABLE symptom (
    id bigint generated BY DEFAULT AS IDENTITY (start WITH 1),
    type VARCHAR(255),
    PRIMARY KEY (id)
);
CREATE TABLE symptom_time (
    id bigint generated BY DEFAULT AS IDENTITY (start WITH 1),
    severity VARCHAR(255),
    timestamp TIMESTAMP,
    symptom_id bigint NOT NULL,
    PRIMARY KEY (id)
);
CREATE TABLE video (
    id bigint generated BY DEFAULT AS IDENTITY (start WITH 1),
    duration bigint NOT NULL, name VARCHAR(255),
    url VARCHAR(255),
    PRIMARY KEY (id)
);

ALTER TABLE check_in_symptom_times
    ADD CONSTRAINT UK_6fm5o4895gahlv0lat4d4hd62
    UNIQUE (symptom_times_id);
ALTER TABLE doctor_roles
    ADD CONSTRAINT UK_67ehbjg4fh98tglqeq49jjfmi
    UNIQUE (roles_id);
ALTER TABLE intake_time
    ADD CONSTRAINT UK_mnp8fll094rsa14513e389c5j
    UNIQUE (medication_id);
ALTER TABLE medication_intake_times
    ADD CONSTRAINT UK_pdxxdl69s7ivdqy3kf5dqyony
    UNIQUE (intake_times_id);
ALTER TABLE patient_medications
    ADD CONSTRAINT UK_9y3bq8dhffumt1pajaq8cd9u3
    UNIQUE (medications_id);
ALTER TABLE patient_roles
    ADD CONSTRAINT UK_nbcaajm252j5o790kckb2eaoh
    UNIQUE (roles_id);
ALTER TABLE symptom_time
    ADD CONSTRAINT UK_oqo9525njw9mj7w4cc8q8w1jp
    UNIQUE (symptom_id);
ALTER TABLE check_in_symptom_times
    ADD CONSTRAINT FK_6fm5o4895gahlv0lat4d4hd62
    FOREIGN KEY (symptom_times_id)
    REFERENCES symptom;
ALTER TABLE check_in_symptom_times
    ADD CONSTRAINT FK_54m0bfk7x4yrraa79in1nnpx2
    FOREIGN KEY (check_in_id)
    REFERENCES check_in;
ALTER TABLE checkin_intaketime
    ADD CONSTRAINT FK_jpc9k6yxa15pghx0rwjgx1oy4
    FOREIGN KEY (intaketime_id)
    REFERENCES intake_time;
ALTER TABLE checkin_intaketime
    ADD CONSTRAINT FK_inb7f3ypnnk84hsrjkc6n94ac
    FOREIGN KEY (checkin_id)
    REFERENCES check_in;
ALTER TABLE doctor_roles
    ADD CONSTRAINT FK_67ehbjg4fh98tglqeq49jjfmi
    FOREIGN KEY (roles_id)
    REFERENCES role;
ALTER TABLE doctor_roles
    ADD CONSTRAINT FK_ewkukxsqibtcsdbsfmhvi430c
    FOREIGN KEY (doctor_id)
    REFERENCES doctor
ALTER TABLE intake_time
    ADD CONSTRAINT FK_mnp8fll094rsa14513e389c5j
    FOREIGN KEY (medication_id)
    REFERENCES medication;
ALTER TABLE medication
    ADD CONSTRAINT FK_69uod9am6erw99lfu6669xgqx
    FOREIGN KEY (medicament_id)
    REFERENCES medicament;
ALTER TABLE medication_intake_times
    ADD CONSTRAINT FK_pdxxdl69s7ivdqy3kf5dqyony
    FOREIGN KEY (intake_times_id)
    REFERENCES intake_time;
ALTER TABLE medication_intake_times
    ADD CONSTRAINT FK_q94ilee8bn7pedid6ddwlhqx3
    FOREIGN KEY (medication_id)
    REFERENCES medication;
ALTER TABLE patient
    ADD CONSTRAINT FK_ftmlhxuasyiusobc21nkp9m77
    FOREIGN KEY (check_in_id)
    REFERENCES check_in;
ALTER TABLE patient_doctor
    ADD CONSTRAINT FK_1577y40iq0nxwelbf0nqcopjb
    FOREIGN KEY (doctor_id)
    REFERENCES doctor;
ALTER TABLE patient_doctor
    ADD CONSTRAINT FK_fkiendjtkiudqumsp6pg917yq
    FOREIGN KEY (patient_id)
    REFERENCES patient;
ALTER TABLE patient_medications
    ADD CONSTRAINT FK_9y3bq8dhffumt1pajaq8cd9u3
    FOREIGN KEY (medications_id)
    REFERENCES medication;
ALTER TABLE patient_medications
    ADD CONSTRAINT FK_bpct2c9nwwunwukmaiqga83d7
    FOREIGN KEY (patient_id)
    REFERENCES patient;
ALTER TABLE patient_roles
    ADD CONSTRAINT FK_nbcaajm252j5o790kckb2eaoh
    FOREIGN KEY (roles_id)
    REFERENCES role;
ALTER TABLE patient_roles
    ADD CONSTRAINT FK_gjaa52j07malojgu5yr7ghifh
    FOREIGN KEY (patient_id)
    REFERENCES patient;
ALTER TABLE symptom_time
    ADD CONSTRAINT FK_oqo9525njw9mj7w4cc8q8w1jp
    FOREIGN KEY (symptom_id)
    REFERENCES symptom;
